### ISSUE TITLE
ValidateCustomResource failed for map with additionalProperties of string type

### ISSUE THREAD

**Issue by yongxiu** [kubernetes/apiextensions-apiserver#53] opened 2021-07-16 01:59 UTC
I wrote an example test https://github.com/kubernetes/apiextensions-apiserver/pull/52/files

According to https://spec.openapis.org/oas/v3.0.3#model-with-map-dictionary-properties, I should be able to validate a map with string type value using 
```
{
  "type": "object",
  "additionalProperties": {
    "type": "string"
  }
}
```

But this test is failing with error: `unexpected validation error for map[field:map[a:b]]: [field: Invalid value: "a": field.a in body is a forbidden property]`

**Comment by Jefftree** [comment] 2021-08-30 19:31
Closing this as it is duplicate of kubernetes/kubernetes#104137

/close

**Closed** 2023-01-09 23:54 UTC
Labels: lifecycle/rotten
